version: "3"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
     - MYSQL_ROOT_PASSWORD=123456
     - MYSQL_DATABASE=rnwl_db
    expose:
      - "3306"
    ports:
     - 3306:3306
    volumes:
     - db:/var/lib/mysql
  app:
    depends_on:
     - mysqldb
    build: ./
    restart: unless-stopped
    ports:
     - 3000:3000
    environment:
     - DB_HOST=mysqldb
     - DB_USER=root
     - DB_PASSWORD=123456
     - DB_NAME=rnwl_db
     - DB_PORT=3306
    stdin_open: true
    tty: true
volumes:
  db:
